name: example
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animated_marker:
    path: ../
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.9.0
  google_maps_flutter_platform_interface: 2.9.5
  google_maps_flutter_android: 2.14.10

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
